# Generated by Django 6.0.3 on 2026-05-13 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_student_nickname_alter_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='faculty',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='university.faculty'),
        ),
    ]
