# Generated by Django 6.0.3 on 2026-05-13 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_remove_location_faculty_faculty_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='faculty',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.faculty'),
        ),
    ]
