# Generated by Django 6.0.3 on 2026-05-10 18:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_location_remove_faculty_city_remove_faculty_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))]),
        ),
    ]
