# Generated by Django 6.0.3 on 2026-05-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_remove_faculty_location_location_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='faculty',
        ),
        migrations.AddField(
            model_name='faculty',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.location'),
        ),
    ]
